// packages/react/src/index.ts
import { useState } from "react";
import { StagingFunction, ScenariosContext, scenarios } from "@flowcards/core";

export * from '@flowcards/core';

export function useScenarios(stagingFunction: StagingFunction) : ScenariosContext {
    const [state, setState] = useState((): ScenariosContext => scenarios(stagingFunction, (a: ScenariosContext): void => { setState(a) }, false));
    return state;
}

// packages/angular/src/index.ts
import { Injectable } from "@angular/core";
import * as Rx from "rxjs";
import { scenarios, ScenariosContext, StagingFunction } from "@flowcards/core";

@Injectable()
export class Scenarios {
  public state?: Rx.Observable<ScenariosContext>;

  public init(stagingFunction: StagingFunction) {
    const subject = new Rx.BehaviorSubject<ScenariosContext>(
      scenarios(
        stagingFunction,
        (a: ScenariosContext): void => {
          subject.next(a);
        },
        false
      )
    );
    this.state = subject.asObservable();
  }
}
